version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout  
      - run:    while(1){ echo "Working."; start-sleep -seconds 10 }
